on:
  workflow_dispatch:

jobs:
  list-c-drive-folders:
    runs-on: windows-2022
    steps:
      - name: List forlder.
        run: |
          cd "C:\Program Files (x86)"
          dir
        shell: cmd